### PR TITLE
Add skeleton structure

### PR DESCRIPTION
**Pull request by theooprea**
In this PR I:
- added the skeleton structure for the hr files in the public repo

### CODE REVIEW

**Review by razvand — COMMENTED** [review]
Does it make sense to have a folder then a file in each folder? Such as `admin/` and `admin.hr`? Will there be multiple files in those folders?

**Comment by theooprea** [comment]
> Does it make sense to have a folder then a file in each folder? Such as `admin/` and `admin.hr`? Will there be multiple files in those folders?

At some point it may be useful to have different formats for the questions. For now, as we only use hr format we don't need to have another layer / level, should we remove it or keep it case we will need it in the future?

**Comment by razvand** [comment]
> > Does it make sense to have a folder then a file in each folder? Such as `admin/` and `admin.hr`? Will there be multiple files in those folders?
> 
> At some point it may be useful to have different formats for the questions. For now, as we only use hr format we don't need to have another layer / level, should we remove it or keep it case we will need it in the future?

Gotcha. The it's fine by me either way. I approved this PR.

**Review by razvand — APPROVED** [review]
All OK.

**Pull request merged**
